apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploymentapp
  labels: 
    app: deploymentapp
spec:
  replicas: 1   #desired state 
  strategy: 
    type: RollingUpdate
  template:
    metadata: 
      name: deploymentapp 
      labels:
        app: deploymentapp
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:latest
          command: ["/bin/sleep", "3650d"]
          resources: 
            requests:    #starting point of our pod's resource
              cpu: "200m"
              memory: "100Mi"
            limits:      #endpoint point of our pod's resource
              cpu: "300m"
              memory: "200Mi"    
          ports:
            - name: http
              containerPort: 80
              protocol: TCP      
  selector:
    matchLabels:
      app: deploymentapp
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:  
  name: hpa1 
  labels:
    app: hpa1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploymentapp
  minReplicas: 1  #if below 50% scale down to 1
  maxReplicas: 2  #if above 50% scale up to 2
  metrics:  #data metrics parameter
    - type: Resource
      resource:
        name: cpu  #the type of resource to be monitored
        target:
          type: Utilization   #cpu utilization condition
          averageUtilization: 50  #cpu utilization threshold in %
