apiVersion: apisix.apache.org/v2alpha1
kind: ApisixRoute
metadata:
  name: path-based-route
  namespace: ingress-apisix
spec:
  http:
  - name: deployappfront
    match:
      paths:
      - /todo
    backend:
      serviceName: deployappfront
      servicePort: 80
  - name: deployappback
    match:
      paths:
      - /student
    backend:
      serviceName: deployappback
      servicePort: 8080
