apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-routes
spec:
  ingressClassName: apisix
  rules:
    - host: local.navendu.me
      http:
        paths:
          - backend:
              service:
                name: frontendsrv
                port:
                  number: 80
            path: /
            pathType: Exact
          - backend:
              service:
                name: backendsrv
                port:
                  number: 8080
            path: /student
            pathType: Exact
