apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader-binding
  namespace: dev
roleRef: # points to the ClusterRole
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-reader # name of ClusterRole
subjects: # points to the ServiceAccount
- kind: ServiceAccount
  name: dev-serviceaccount # service account to bind to
  namespace: dev # ns of service account