apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: devops
roleRef: # points to the Role
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader # name of Role
subjects: # points to the ServiceAccount
- kind: ServiceAccount
  name: devops-serviceaccount # service account to bind to
  namespace: devops # ns of service account