apiVersion: v1
kind: Pod
metadata:
  name: devops-kubectl
  namespace: devops
spec:
  containers:
  - image: bibinwilson/docker-kubectl:latest
    name: kubectl
  serviceAccountName: devops-serviceaccount