apiVersion: v1
kind: Pod
metadata:
  name: employeenode
  namespace: microstatic
  labels:
    app: employeenode

spec:
  containers:
  - name: employeenode
    image: swapnil0078/employee:micro
    resources: 
        requests:
            cpu: "50m"
            memory: "90Mi" 
    ports:
      - name: http
        containerPort: 3000
        protocol: TCP

---


apiVersion: v1
kind: Service
metadata:
  name: employeenodeport
  namespace: microstatic

spec:
  type: NodePort
  selector:
    app:  employeenode
  ports:
  - port: 3000
    targetPort: 3000
    name: employeenode
    protocol: TCP
