apiVersion: v1
kind: Pod
metadata: 
      name: mypod1
spec:
    containers: 
        - name: container1nginx
          image: nginx:latest
          resources: 
            requests:
              cpu: "50m"
              memory: "90Mi" 
          ports: 
              - containerPort: 80
                name: nginx
                protocol: TCP