apiVersion: v1 
kind: Service
metadata:
        name: clusterip #cluster 
spec:
    selector:
          app: mypod1
    type: ClusterIP
    ports:
    - protocol: TCP
      port: 80
      #targetPort: 80
      name: nginx