apiVersion: v1
kind: Pod
metadata:
  name: studentnode
  namespace: microstatic
  labels:
    app: studentnode

spec:
  containers:
  - name: studentnode
    image: swapnil0078/student:latest
    resources: 
        requests:
            cpu: "50m"
            memory: "90Mi" 
    ports:
      - name: http
        containerPort: 8080
        protocol: TCP

---


apiVersion: v1
kind: Service
metadata:
  name: studentnode
  namespace: microstatic

spec:
  type: NodePort
  selector:
    app: studentnode
  ports:
  - port: 8080
    targetPort: 8080
    name: studentnode
    protocol: TCP
