apiVersion: v1
kind: Pod
metadata:
  name: todo
spec:
  containers:
    - name: contomcat
      image: swapnil0078/student:latest
      resources:
        requests:
          cpu: "50m"
          memory: "90Mi"
      ports:
        - containerPort: 8080
          name: tomcat
          protocol: TCP
