apiVersion: v1
kind: Service
metadata:
  name: todolb
spec:
  selector:
    app: todo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: tomcat
