apiVersion: v1
kind: Pod
metadata: 
      name: todo
spec:
    containers: 
        - name: contodo
          image: swapnil0078/todoapp:latest
          resources: 
            requests:
              cpu: "50m"
              memory: "90Mi" 
          ports: 
              - containerPort: 80
                name: nginx
                protocol: TCP