apiVersion: v1
kind: Service
metadata:
  name: netflixclone
  namespace: clone

spec:
  type: LoadBalancer
  selector:
    app:  netflixclone
  ports:
  - port: 3000
    targetPort: 3000
    name: netflixclone
    protocol: TCP