apiVersion: v1
kind: Service
metadata:
  name: netflixclone

spec:
  type: LoadBalancer
  selector:
    app:  netflixclone
  ports:
  - port: 80
    targetPort: 8081
    name: netflixclone
    protocol: TCP