apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testadminbinding
  namespace: micro
subjects:
- kind: ServiceAccount
  name: webapp
  apiGroup: ""
roleRef:
  kind: Role
  name: testadmin
  apiGroup: ""