apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: myapp  # This Role is limited to the "default" namespace
  name: pod-reader
rules:
- apiGroups: [""]  # "" indicates the core API group (where Pods live)
  resources: ["pods"]
  verbs: ["get", "list"]
