apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: User  # Could also be "ServiceAccount" or "Group"
  name: swapnil  # Name of the user or service account
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader  # Name of the Role created earlier
  apiGroup: rbac.authorization.k8s.io
