apiVersion: apps/v1
kind:  ReplicaSet
metadata: 
       name: mobappreplica
       labels:
            app: mobappreplica
spec: 
    replicas: 3  #how many replica's you want to create on the basis of template
    template:
      metadata:  #like a tag
         labels: 
            app: mobappreplica   #this container template is added to selector to  create replicas.
      spec:
        containers:
            - name: mypod-cont1
              image: nginx:latest
              resources: 
                  requests:
                    cpu: "50m"
                    memory: "90Mi"        
              ports:  
                - name: http
                  containerPort: 80
                  protocol: TCP
    selector: 
          matchExpressions: 
            - {key: app, operator: In, values: [webappreplica, mobappreplica]}